// PP Cloud Media - LED Billboard Locations Data
// Generated from data.csv

const locationsData = [
    {
        id: 1,
        name: "แยกเมญ่า",
        province: "เชียงใหม่",
        region: "north",
        latitude: 18.801254,
        longitude: 98.968402,
        size: "medium",
        dimensions: "7x12 M.",
        showTimes: "06.00 - 24.00 น.",
        timing: "18 Hrs.",
        address: "แยกเมญ่า",
        description: "จอ LED 7x12 M. ตั้งอยู่แยกเมญ่า จังหวัดเชียงใหม่",
        traffic: "high",
        viewersPerDay: 2539500,
    },
    {
        id: 2,
        name: "สี่แยกสะพานนครพิงค์ (เจดีย์ขาว)",
        province: "เชียงใหม่",
        region: "north",
        latitude: 18.7931276,
        longitude: 98.9996019,
        size: "medium",
        dimensions: "6x10 M.",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "สี่แยกสะพานนครพิงค์ (เจดีย์ขาว)",
        description: "จอ LED 6x10 M. ตั้งอยู่สี่แยกสะพานนครพิงค์ (เจดีย์ขาว) จังหวัดเชียงใหม่",
        traffic: "medium",
        viewersPerDay: 1562780,
    },
    {
        id: 3,
        name: "ถนนคนเดิน ท่าแพ",
        province: "เชียงใหม่",
        region: "north",
        latitude: 18.7873869,
        longitude: 98.9937011,
        size: "medium",
        dimensions: "3x4 M.",
        showTimes: "06.00 - 24.00 น.",
        timing: "18 Hrs.",
        address: "ถนนคนเดิน ท่าแพ",
        description: "จอ LED 3x4 M. ตั้งอยู่ถนนคนเดิน ท่าแพ จังหวัดเชียงใหม่",
        traffic: "medium",
        viewersPerDay: 1290000,
    },
    {
        id: 4,
        name: "สี่แยกรวมโชคมีชัย",
        province: "เชียงใหม่",
        region: "north",
        latitude: 18.8229278,
        longitude: 99.0121128,
        size: "medium",
        dimensions: "14x25 M.",
        showTimes: "06.00 - 22.30 น.",
        timing: "16.5 Hrs.",
        address: "สี่แยกรวมโชคมีชัย",
        description: "จอ LED 14x25 M. ตั้งอยู่สี่แยกรวมโชคมีชัย จังหวัดเชียงใหม่",
        traffic: "medium",
        viewersPerDay: 1894170,
    },
    {
        id: 5,
        name: "จอแยกประตูเชียงใหม่ ถ.ราชโยธา",
        province: "เชียงราย",
        region: "north",
        latitude: 19.907778,
        longitude: 99.823944,
        size: "medium",
        dimensions: "5x8 M.",
        showTimes: "07.00 - 21.00 น.",
        timing: "14 Hrs.",
        address: "จอแยกประตูเชียงใหม่ ถ.ราชโยธา",
        description: "จอ LED 5x8 M. ตั้งอยู่จอแยกประตูเชียงใหม่ ถ.ราชโยธา จังหวัดเชียงราย",
        traffic: "high",
        viewersPerDay: 2860000,
    },
    {
        id: 6,
        name: "ห้าแยกพ่อขุน ถ.พหลโยธิน",
        province: "เชียงราย",
        region: "north",
        latitude: 19.9080194,
        longitude: 99.8404476,
        size: "medium",
        dimensions: "6x10 M.",
        showTimes: "07.00 - 20.00 น.",
        timing: "13 Hrs.",
        address: "ห้าแยกพ่อขุน ถ.พหลโยธิน",
        description: "จอ LED 6x10 M. ตั้งอยู่ห้าแยกพ่อขุน ถ.พหลโยธิน จังหวัดเชียงราย",
        traffic: "high",
        viewersPerDay: 2460000,
    },
    {
        id: 7,
        name: "ถ.ยันตรกิจโกศล (หน้าร้านเนรมิตคัลเลอร์แล็ป)",
        province: "แพร่",
        region: "north",
        latitude: 18.1368352,
        longitude: 100.1471158,
        size: "medium",
        dimensions: "3x5 M.",
        showTimes: "06:00 - 22:00 น.",
        timing: "16 Hrs.",
        address: "ถ.ยันตรกิจโกศล (หน้าร้านเนรมิตคัลเลอร์แล็ป)",
        description: "จอ LED 3x5 M. ตั้งอยู่ถ.ยันตรกิจโกศล (หน้าร้านเนรมิตคัลเลอร์แล็ป) จังหวัดแพร่",
        traffic: "low",
        viewersPerDay: 724500,
    },
    {
        id: 8,
        name: "ถ.มุขมนตรี (ตลาดสวายเรียง)",
        province: "นครราชสีมา",
        region: "northeast",
        latitude: 14.97279,
        longitude: 102.073,
        size: "medium",
        dimensions: "5x8 M.",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "ถ.มุขมนตรี (ตลาดสวายเรียง)",
        description: "จอ LED 5x8 M. ตั้งอยู่ถ.มุขมนตรี (ตลาดสวายเรียง) จังหวัดนครราชสีมา",
        traffic: "medium",
        viewersPerDay: 1495250,
    },
    {
        id: 9,
        name: "ถ.มิตรภาพ (ปากช่อง)",
        province: "นครราชสีมา",
        region: "northeast",
        latitude: 14.660937,
        longitude: 101.392833,
        size: "xlarge",
        dimensions: "10 x 19",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "ถ.มิตรภาพ (ปากช่อง)",
        description: "จอ LED 10 x 19 ตั้งอยู่ถ.มิตรภาพ (ปากช่อง) จังหวัดนครราชสีมา",
        traffic: "very_high",
        viewersPerDay: 6142250,
    },
    {
        id: 10,
        name: "ตลาดโต้รุ่งขอนแก่น (ถนนรื่นรมย์)",
        province: "ขอนแก่น",
        region: "northeast",
        latitude: 16.425652,
        longitude: 102.8350492,
        size: "medium",
        dimensions: "7x12 M.",
        showTimes: "07.00 - 22.00 น.",
        timing: "15 Hrs.",
        address: "ตลาดโต้รุ่งขอนแก่น (ถนนรื่นรมย์)",
        description: "จอ LED 7x12 M. ตั้งอยู่ตลาดโต้รุ่งขอนแก่น (ถนนรื่นรมย์) จังหวัดขอนแก่น",
        traffic: "medium",
        viewersPerDay: 1488250,
    },
    {
        id: 11,
        name: "ตึกสีฟ้า สี่แยกสามเหลี่ยม ติดถนนมิตรภาพ",
        province: "ขอนแก่น",
        region: "northeast",
        latitude: 16.4392893,
        longitude: 102.8286756,
        size: "medium",
        dimensions: "8x6 M.",
        showTimes: "07.30 - 20.00 น. พักจอ 09.00 - 10.00 และ 14.00 - 15.00",
        timing: "10.5 Hrs.",
        address: "ตึกสีฟ้า สี่แยกสามเหลี่ยม ติดถนนมิตรภาพ",
        description: "จอ LED 8x6 M. ตั้งอยู่ตึกสีฟ้า สี่แยกสามเหลี่ยม ติดถนนมิตรภาพ จังหวัดขอนแก่น",
        traffic: "medium",
        viewersPerDay: 1542780,
    },
    {
        id: 12,
        name: "แยกสามพร้าว",
        province: "อุดรธานี",
        region: "northeast",
        latitude: 17.427413,
        longitude: 102.8111971,
        size: "medium",
        dimensions: "13x6 M.",
        showTimes: "06.30 - 22.30 น.",
        timing: "16 Hrs.",
        address: "แยกสามพร้าว",
        description: "จอ LED 13x6 M. ตั้งอยู่แยกสามพร้าว จังหวัดอุดรธานี",
        traffic: "low",
        viewersPerDay: 921328,
    },
    {
        id: 13,
        name: "แยกบ้านจั่น",
        province: "อุดรธานี",
        region: "northeast",
        latitude: 17.36399425,
        longitude: 102.8158981,
        size: "medium",
        dimensions: "24x11.5 M.",
        showTimes: "07.00 - 20.00 น.",
        timing: "13 Hrs.",
        address: "แยกบ้านจั่น",
        description: "จอ LED 24x11.5 M. ตั้งอยู่แยกบ้านจั่น จังหวัดอุดรธานี",
        traffic: "high",
        viewersPerDay: 2420000,
    },
    {
        id: 14,
        name: "สี่แยก ถ.พิทักษ์ ตัดกับ ถ.รมย์บุรี",
        province: "บุรีรัมย์",
        region: "northeast",
        latitude: 14.997481,
        longitude: 103.1080508,
        size: "medium",
        dimensions: "4x6 M.",
        showTimes: "07.00 - 22.00 น.",
        timing: "15 Hrs.",
        address: "สี่แยก ถ.พิทักษ์ ตัดกับ ถ.รมย์บุรี",
        description: "จอ LED 4x6 M. ตั้งอยู่สี่แยก ถ.พิทักษ์ ตัดกับ ถ.รมย์บุรี จังหวัดบุรีรัมย์",
        traffic: "medium",
        viewersPerDay: 1017300,
    },
    {
        id: 15,
        name: "สี่แยกโรงเรียนเมืองร้อยเอ็ด ถ.ปัทมานนท์",
        province: "ร้อยเอ็ด",
        region: "northeast",
        latitude: 16.0455486,
        longitude: 103.646959,
        size: "medium",
        dimensions: "5x11 M.",
        showTimes: "06.30 - 21.30 น.",
        timing: "15 Hrs.",
        address: "สี่แยกโรงเรียนเมืองร้อยเอ็ด ถ.ปัทมานนท์",
        description: "จอ LED 5x11 M. ตั้งอยู่สี่แยกโรงเรียนเมืองร้อยเอ็ด ถ.ปัทมานนท์ จังหวัดร้อยเอ็ด",
        traffic: "medium",
        viewersPerDay: 1465000,
    },
    {
        id: 16,
        name: "สี่แยก ถ.เทศบาล1 ตัดกับ ถ.หมอกวน",
        province: "สุรินทร์",
        region: "northeast",
        latitude: 14.88086,
        longitude: 103.50614,
        size: "medium",
        dimensions: "5x8 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "สี่แยก ถ.เทศบาล1 ตัดกับ ถ.หมอกวน",
        description: "จอ LED 5x8 M. ตั้งอยู่สี่แยก ถ.เทศบาล1 ตัดกับ ถ.หมอกวน จังหวัดสุรินทร์",
        traffic: "medium",
        viewersPerDay: 1298928,
    },
    {
        id: 17,
        name: "ถ.กวงเฮง (ใกล้ห้างซุ่นเฮงพลาซ่า)",
        province: "ศรีสะเกษ",
        region: "northeast",
        latitude: 15.114497,
        longitude: 104.3288663,
        size: "medium",
        dimensions: "4x6 M.",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "ถ.กวงเฮง (ใกล้ห้างซุ่นเฮงพลาซ่า)",
        description: "จอ LED 4x6 M. ตั้งอยู่ถ.กวงเฮง (ใกล้ห้างซุ่นเฮงพลาซ่า) จังหวัดศรีสะเกษ",
        traffic: "low",
        viewersPerDay: 976400,
    },
    {
        id: 18,
        name: "สี่แยกวนารมย์",
        province: "อุบลราชธานี",
        region: "northeast",
        latitude: 15.274699,
        longitude: 104.841845,
        size: "medium",
        dimensions: "8x14 M.",
        showTimes: "07.00 - 21.00 น.",
        timing: "14 Hrs.",
        address: "สี่แยกวนารมย์",
        description: "จอ LED 8x14 M. ตั้งอยู่สี่แยกวนารมย์ จังหวัดอุบลราชธานี",
        traffic: "high",
        viewersPerDay: 2064447,
    },
    {
        id: 19,
        name: "สุนีย์ทาวเวอร์ (หน้าตึกฝั่งกสิกร)",
        province: "อุบลราชธานี",
        region: "northeast",
        latitude: 15.2567184,
        longitude: 104.8475344,
        size: "medium",
        dimensions: "3.5x6 M.",
        showTimes: "06.00 - 22.30 น.",
        timing: "16.5 Hrs.",
        address: "สุนีย์ทาวเวอร์ (หน้าตึกฝั่งกสิกร)",
        description: "จอ LED 3.5x6 M. ตั้งอยู่สุนีย์ทาวเวอร์ (หน้าตึกฝั่งกสิกร) จังหวัดอุบลราชธานี",
        traffic: "medium",
        viewersPerDay: 1864447,
    },
    {
        id: 20,
        name: "สุนีย์ทาวเวอร์ (หน้าตึกฝั่งเคเอฟซี)",
        province: "อุบลราชธานี",
        region: "northeast",
        latitude: 15.2566294,
        longitude: 104.8475357,
        size: "medium",
        dimensions: "3.5x6 M.",
        showTimes: "06.00 - 22.30 น.",
        timing: "16.5 Hrs.",
        address: "สุนีย์ทาวเวอร์ (หน้าตึกฝั่งเคเอฟซี)",
        description: "จอ LED 3.5x6 M. ตั้งอยู่สุนีย์ทาวเวอร์ (หน้าตึกฝั่งเคเอฟซี) จังหวัดอุบลราชธานี",
        traffic: "medium",
        viewersPerDay: 1864447,
    },
    {
        id: 21,
        name: "แยกโรงพยาบาลชัยภูมิ",
        province: "ชัยภูมิ",
        region: "northeast",
        latitude: 15.8065597,
        longitude: 102.0356706,
        size: "medium",
        dimensions: "3x4 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "แยกโรงพยาบาลชัยภูมิ",
        description: "จอ LED 3x4 M. ตั้งอยู่แยกโรงพยาบาลชัยภูมิ จังหวัดชัยภูมิ",
        traffic: "low",
        viewersPerDay: 897793,
    },
    {
        id: 22,
        name: "แยกโรงเรียนสตรีชัยภูมิ",
        province: "ชัยภูมิ",
        region: "northeast",
        latitude: 15.8070529,
        longitude: 102.0286881,
        size: "medium",
        dimensions: "3x4 M.",
        showTimes: "",
        timing: "",
        address: "แยกโรงเรียนสตรีชัยภูมิ",
        description: "จอ LED 3x4 M. ตั้งอยู่แยกโรงเรียนสตรีชัยภูมิ จังหวัดชัยภูมิ",
        traffic: "low",
        viewersPerDay: 897250,
    },
    {
        id: 23,
        name: "หน้าห้างเสริมไทยพลาซ่า",
        province: "มหาสารคาม",
        region: "northeast",
        latitude: 16.1806725,
        longitude: 103.3023541,
        size: "medium",
        dimensions: "4x6 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "หน้าห้างเสริมไทยพลาซ่า",
        description: "จอ LED 4x6 M. ตั้งอยู่หน้าห้างเสริมไทยพลาซ่า จังหวัดมหาสารคาม",
        traffic: "low",
        viewersPerDay: 895567,
    },
    {
        id: 24,
        name: "สี่แยก ถ.สถลเชียงคาน-ร่วมใจ",
        province: "เลย",
        region: "northeast",
        latitude: 17.4902647,
        longitude: 101.728606,
        size: "medium",
        dimensions: "3x4 M.",
        showTimes: "08.00 - 22.00 น.",
        timing: "14 Hrs.",
        address: "สี่แยก ถ.สถลเชียงคาน-ร่วมใจ",
        description: "จอ LED 3x4 M. ตั้งอยู่สี่แยก ถ.สถลเชียงคาน-ร่วมใจ จังหวัดเลย",
        traffic: "low",
        viewersPerDay: 627450,
    },
    {
        id: 25,
        name: "สี่แยกหอนาฬิกา",
        province: "อำนาจเจริญ",
        region: "northeast",
        latitude: 15.863913,
        longitude: 104.628113,
        size: "medium",
        dimensions: "5x8 M.",
        showTimes: "07.00 - 21.00 น.",
        timing: "14 Hrs.",
        address: "สี่แยกหอนาฬิกา",
        description: "จอ LED 5x8 M. ตั้งอยู่สี่แยกหอนาฬิกา จังหวัดอำนาจเจริญ",
        traffic: "low",
        viewersPerDay: 887560,
    },
    {
        id: 26,
        name: "สี่แยกตลาดมหาชัย",
        province: "สมุทรสาคร",
        region: "central",
        latitude: 13.5497136,
        longitude: 100.2741822,
        size: "medium",
        dimensions: "7x10 M.",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "สี่แยกตลาดมหาชัย",
        description: "จอ LED 7x10 M. ตั้งอยู่สี่แยกตลาดมหาชัย จังหวัดสมุทรสาคร",
        traffic: "medium",
        viewersPerDay: 1454800,
    },
    {
        id: 27,
        name: "ถนนสุขุมวิทตัดแยกเทพารักษ์",
        province: "สมุทรปราการ",
        region: "central",
        latitude: 13.644726,
        longitude: 100.594795,
        size: "medium",
        dimensions: "10x12 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "ถนนสุขุมวิทตัดแยกเทพารักษ์",
        description: "จอ LED 10x12 M. ตั้งอยู่ถนนสุขุมวิทตัดแยกเทพารักษ์ จังหวัดสมุทรปราการ",
        traffic: "very_high",
        viewersPerDay: 6000000,
    },
    {
        id: 28,
        name: "แยกเทพารักษ์ ถ.ศรีนครินทร์",
        province: "สมุทรปราการ",
        region: "central",
        latitude: 13.626173,
        longitude: 100.626482,
        size: "medium",
        dimensions: "8x15 M.",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "แยกเทพารักษ์ ถ.ศรีนครินทร์",
        description: "จอ LED 8x15 M. ตั้งอยู่แยกเทพารักษ์ ถ.ศรีนครินทร์ จังหวัดสมุทรปราการ",
        traffic: "very_high",
        viewersPerDay: 6000000,
    },
    {
        id: 29,
        name: "ห้าแยกปากเกร็ด",
        province: "นนทบุรี",
        region: "central",
        latitude: 13.907673,
        longitude: 100.503896,
        size: "medium",
        dimensions: "7x12 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "ห้าแยกปากเกร็ด",
        description: "จอ LED 7x12 M. ตั้งอยู่ห้าแยกปากเกร็ด จังหวัดนนทบุรี",
        traffic: "high",
        viewersPerDay: 2040000,
    },
    {
        id: 30,
        name: "แยกต่างระดับบางสีทอง ถ.นครอินทร์",
        province: "นนทบุรี",
        region: "central",
        latitude: 13.82451,
        longitude: 100.47994,
        size: "xlarge",
        dimensions: "8 x 15.5",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "แยกต่างระดับบางสีทอง ถ.นครอินทร์",
        description: "จอ LED 8 x 15.5 ตั้งอยู่แยกต่างระดับบางสีทอง ถ.นครอินทร์ จังหวัดนนทบุรี",
        traffic: "high",
        viewersPerDay: 2040000,
    },
    {
        id: 31,
        name: "ถนนเทพคุณากร มุ่งหน้าวัดโสธรฯ",
        province: "ฉะเชิงเทรา",
        region: "central",
        latitude: 13.67339,
        longitude: 101.0631,
        size: "medium",
        dimensions: "6x9 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "ถนนเทพคุณากร มุ่งหน้าวัดโสธรฯ",
        description: "จอ LED 6x9 M. ตั้งอยู่ถนนเทพคุณากร มุ่งหน้าวัดโสธรฯ จังหวัดฉะเชิงเทรา",
        traffic: "medium",
        viewersPerDay: 1047300,
    },
    {
        id: 32,
        name: "แยกพหลโยธิน (ขาเข้า นครสวรรค์-พิษณุโลก)",
        province: "นครสวรรค์",
        region: "central",
        latitude: 15.7102262,
        longitude: 100.1175883,
        size: "medium",
        dimensions: "10x17 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "แยกพหลโยธิน (ขาเข้า นครสวรรค์-พิษณุโลก)",
        description: "จอ LED 10x17 M. ตั้งอยู่แยกพหลโยธิน (ขาเข้า นครสวรรค์-พิษณุโลก) จังหวัดนครสวรรค์",
        traffic: "high",
        viewersPerDay: 2597452,
    },
    {
        id: 33,
        name: "ห้าแยกตลาดโคกมะตูม",
        province: "พิษณุโลก",
        region: "central",
        latitude: 16.8163151,
        longitude: 100.2722107,
        size: "medium",
        dimensions: "4x7 M.",
        showTimes: "08.30 - 20.30 น.",
        timing: "12 Hrs.",
        address: "ห้าแยกตลาดโคกมะตูม",
        description: "จอ LED 4x7 M. ตั้งอยู่ห้าแยกตลาดโคกมะตูม จังหวัดพิษณุโลก",
        traffic: "medium",
        viewersPerDay: 1059110,
    },
    {
        id: 34,
        name: "ถ.สีหราชเดโชชัย มุ่งหน้านครสวรรค์",
        province: "พิษณุโลก",
        region: "central",
        latitude: 16.799631,
        longitude: 100.214399,
        size: "xlarge",
        dimensions: "10 x 19",
        showTimes: "07.00 - 21.00 น.",
        timing: "15 Hrs.",
        address: "ถ.สีหราชเดโชชัย มุ่งหน้านครสวรรค์",
        description: "จอ LED 10 x 19 ตั้งอยู่ถ.สีหราชเดโชชัย มุ่งหน้านครสวรรค์ จังหวัดพิษณุโลก",
        traffic: "very_high",
        viewersPerDay: 3006720,
    },
    {
        id: 35,
        name: "จอถนนพระพันวษา",
        province: "สุพรรณบุรี",
        region: "central",
        latitude: 14.4715752,
        longitude: 100.1165286,
        size: "medium",
        dimensions: "3x5 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "จอถนนพระพันวษา",
        description: "จอ LED 3x5 M. ตั้งอยู่จอถนนพระพันวษา จังหวัดสุพรรณบุรี",
        traffic: "medium",
        viewersPerDay: 1176030,
    },
    {
        id: 36,
        name: "สี่แยกนางพิม",
        province: "สุพรรณบุรี",
        region: "central",
        latitude: 14.472372,
        longitude: 100.116767,
        size: "medium",
        dimensions: "3x4 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "สี่แยกนางพิม",
        description: "จอ LED 3x4 M. ตั้งอยู่สี่แยกนางพิม จังหวัดสุพรรณบุรี",
        traffic: "medium",
        viewersPerDay: 1186000,
    },
    {
        id: 37,
        name: "สามแยกคลอง 5 (คลองหลวง)",
        province: "ปทุมธานี",
        region: "central",
        latitude: 14.06727,
        longitude: 100.70995,
        size: "medium",
        dimensions: "3x5 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "สามแยกคลอง 5 (คลองหลวง)",
        description: "จอ LED 3x5 M. ตั้งอยู่สามแยกคลอง 5 (คลองหลวง) จังหวัดปทุมธานี",
        traffic: "high",
        viewersPerDay: 2858047,
    },
    {
        id: 38,
        name: "ถ.ลำลูกกาคลอง 2",
        province: "ปทุมธานี",
        region: "central",
        latitude: 13.946369,
        longitude: 100.64276,
        size: "xlarge",
        dimensions: "10 x 19",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "ถ.ลำลูกกาคลอง 2",
        description: "จอ LED 10 x 19 ตั้งอยู่ถ.ลำลูกกาคลอง 2 จังหวัดปทุมธานี",
        traffic: "high",
        viewersPerDay: 2858192,
    },
    {
        id: 39,
        name: "ถ.พหลโยธิน แยกวังน้อย (ขาออกกรุงเทพ)",
        province: "อยุธยา",
        region: "central",
        latitude: 14.185046,
        longitude: 100.629108,
        size: "medium",
        dimensions: "5x9 M.",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "ถ.พหลโยธิน แยกวังน้อย (ขาออกกรุงเทพ)",
        description: "จอ LED 5x9 M. ตั้งอยู่ถ.พหลโยธิน แยกวังน้อย (ขาออกกรุงเทพ) จังหวัดอยุธยา",
        traffic: "very_high",
        viewersPerDay: 3300000,
    },
    {
        id: 40,
        name: "ถ.พหลโยธิน แยกวังน้อย (ขาเข้ากรุงเทพ)",
        province: "อยุธยา",
        region: "central",
        latitude: 14.185046,
        longitude: 100.629108,
        size: "medium",
        dimensions: "5x9 M.",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "ถ.พหลโยธิน แยกวังน้อย (ขาเข้ากรุงเทพ)",
        description: "จอ LED 5x9 M. ตั้งอยู่ถ.พหลโยธิน แยกวังน้อย (ขาเข้ากรุงเทพ) จังหวัดอยุธยา",
        traffic: "very_high",
        viewersPerDay: 3300000,
    },
    {
        id: 41,
        name: "ถ.สายเอเชีย (ขาออก)",
        province: "อยุธยา",
        region: "central",
        latitude: 14.335359,
        longitude: 100.612459,
        size: "xlarge",
        dimensions: "10 x 19",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "ถ.สายเอเชีย (ขาออก)",
        description: "จอ LED 10 x 19 ตั้งอยู่ถ.สายเอเชีย (ขาออก) จังหวัดอยุธยา",
        traffic: "very_high",
        viewersPerDay: 3305580,
    },
    {
        id: 42,
        name: "ถนนศึกษาเจริญ",
        province: "เพชรบูรณ์",
        region: "central",
        latitude: 16.41839,
        longitude: 101.15471,
        size: "medium",
        dimensions: "3x5 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "ถนนศึกษาเจริญ",
        description: "จอ LED 3x5 M. ตั้งอยู่ถนนศึกษาเจริญ จังหวัดเพชรบูรณ์",
        traffic: "medium",
        viewersPerDay: 1321584,
    },
    {
        id: 43,
        name: "ถ.มิตรภาพ (ขาออก)",
        province: "สระบุรี",
        region: "central",
        latitude: 14.520996,
        longitude: 100.922534,
        size: "xlarge",
        dimensions: "10 x 19",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "ถ.มิตรภาพ (ขาออก)",
        description: "จอ LED 10 x 19 ตั้งอยู่ถ.มิตรภาพ (ขาออก) จังหวัดสระบุรี",
        traffic: "very_high",
        viewersPerDay: 5452800,
    },
    {
        id: 44,
        name: "แยกสุขุมวิทพัทยาใต้",
        province: "ชลบุรี",
        region: "east",
        latitude: 12.91781,
        longitude: 100.89687,
        size: "medium",
        dimensions: "8x14 M.",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "แยกสุขุมวิทพัทยาใต้",
        description: "จอ LED 8x14 M. ตั้งอยู่แยกสุขุมวิทพัทยาใต้ จังหวัดชลบุรี",
        traffic: "high",
        viewersPerDay: 2126000,
    },
    {
        id: 45,
        name: "สามแยกเทพประสิทธิ์",
        province: "ชลบุรี",
        region: "east",
        latitude: 12.9043923,
        longitude: 100.8694317,
        size: "medium",
        dimensions: "10x15 M.",
        showTimes: "07.00 - 23.00 น.",
        timing: "16 Hrs.",
        address: "สามแยกเทพประสิทธิ์",
        description: "จอ LED 10x15 M. ตั้งอยู่สามแยกเทพประสิทธิ์ จังหวัดชลบุรี",
        traffic: "medium",
        viewersPerDay: 1592500,
    },
    {
        id: 46,
        name: "แยกพัทยาเหนือ ถนนสุขุมวิท 2",
        province: "ชลบุรี",
        region: "east",
        latitude: 12.948651,
        longitude: 100.905839,
        size: "medium",
        dimensions: "10x5 M.",
        showTimes: "06.00 - 24.00 น.",
        timing: "18 Hrs.",
        address: "แยกพัทยาเหนือ ถนนสุขุมวิท 2",
        description: "จอ LED 10x5 M. ตั้งอยู่แยกพัทยาเหนือ ถนนสุขุมวิท 2 จังหวัดชลบุรี",
        traffic: "medium",
        viewersPerDay: 1902100,
    },
    {
        id: 47,
        name: "แยกเทพประสิทธิ์ ถนนสุขุมวิท 2",
        province: "ชลบุรี",
        region: "east",
        latitude: 12.909075,
        longitude: 100.89633,
        size: "medium",
        dimensions: "14x6 M.",
        showTimes: "06.00 - 24.00 น.",
        timing: "18 Hrs.",
        address: "แยกเทพประสิทธิ์ ถนนสุขุมวิท 2",
        description: "จอ LED 14x6 M. ตั้งอยู่แยกเทพประสิทธิ์ ถนนสุขุมวิท 2 จังหวัดชลบุรี",
        traffic: "medium",
        viewersPerDay: 1621000,
    },
    {
        id: 48,
        name: "แยกชลชาย",
        province: "ชลบุรี",
        region: "east",
        latitude: 13.3492267,
        longitude: 100.9797535,
        size: "medium",
        dimensions: "9x17 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "แยกชลชาย",
        description: "จอ LED 9x17 M. ตั้งอยู่แยกชลชาย จังหวัดชลบุรี",
        traffic: "high",
        viewersPerDay: 2539450,
    },
    {
        id: 49,
        name: "ถนนสุขุมวิท มุ่งหน้ากรุงเทพฯ",
        province: "ชลบุรี",
        region: "east",
        latitude: 13.339232,
        longitude: 100.973029,
        size: "xlarge",
        dimensions: "10 x 19",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "ถนนสุขุมวิท มุ่งหน้ากรุงเทพฯ",
        description: "จอ LED 10 x 19 ตั้งอยู่ถนนสุขุมวิท มุ่งหน้ากรุงเทพฯ จังหวัดชลบุรี",
        traffic: "high",
        viewersPerDay: 2478900,
    },
    {
        id: 50,
        name: "แยกทับมา ถ.สุขุมวิท-บายพาส",
        province: "ระยอง",
        region: "east",
        latitude: 12.704618,
        longitude: 101.2413983,
        size: "medium",
        dimensions: "8x15 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "แยกทับมา ถ.สุขุมวิท-บายพาส",
        description: "จอ LED 8x15 M. ตั้งอยู่แยกทับมา ถ.สุขุมวิท-บายพาส จังหวัดระยอง",
        traffic: "medium",
        viewersPerDay: 1152081,
    },
    {
        id: 51,
        name: "แยกเนินสำลี",
        province: "ระยอง",
        region: "east",
        latitude: 12.703048,
        longitude: 101.1859001,
        size: "medium",
        dimensions: "8x13 M.",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "แยกเนินสำลี",
        description: "จอ LED 8x13 M. ตั้งอยู่แยกเนินสำลี จังหวัดระยอง",
        traffic: "low",
        viewersPerDay: 956000,
    },
    {
        id: 52,
        name: "แยก PMY",
        province: "ระยอง",
        region: "east",
        latitude: 12.6834054,
        longitude: 101.2385624,
        size: "medium",
        dimensions: "4x6 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "แยก PMY",
        description: "จอ LED 4x6 M. ตั้งอยู่แยก PMY จังหวัดระยอง",
        traffic: "low",
        viewersPerDay: 932637,
    },
    {
        id: 53,
        name: "ถนนศูนย์การค้าสาย 4",
        province: "ระยอง",
        region: "east",
        latitude: 12.6819847,
        longitude: 101.2714745,
        size: "medium",
        dimensions: "4x6 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "ถนนศูนย์การค้าสาย 4",
        description: "จอ LED 4x6 M. ตั้งอยู่ถนนศูนย์การค้าสาย 4 จังหวัดระยอง",
        traffic: "low",
        viewersPerDay: 932637,
    },
    {
        id: 54,
        name: "สี่แยกโรงแรมคามิโอ",
        province: "ระยอง",
        region: "east",
        latitude: 12.682888,
        longitude: 101.2613024,
        size: "medium",
        dimensions: "6.5x10 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "สี่แยกโรงแรมคามิโอ",
        description: "จอ LED 6.5x10 M. ตั้งอยู่สี่แยกโรงแรมคามิโอ จังหวัดระยอง",
        traffic: "low",
        viewersPerDay: 932637,
    },
    {
        id: 55,
        name: "จอสามแยก มาสด้า",
        province: "จันทบุรี",
        region: "east",
        latitude: 12.598512,
        longitude: 102.118774,
        size: "medium",
        dimensions: "4x5 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "จอสามแยก มาสด้า",
        description: "จอ LED 4x5 M. ตั้งอยู่จอสามแยก มาสด้า จังหวัดจันทบุรี",
        traffic: "medium",
        viewersPerDay: 1175490,
    },
    {
        id: 56,
        name: "สี่แยกตลาดฉัตรไชย ถ.เพชรเกษม",
        province: "ประจวบคีรีขันธ์",
        region: "west",
        latitude: 12.5729456,
        longitude: 99.955718,
        size: "medium",
        dimensions: "6x4 M.",
        showTimes: "7.30 - 22.00 น.",
        timing: "14.5 Hrs.",
        address: "สี่แยกตลาดฉัตรไชย ถ.เพชรเกษม",
        description: "จอ LED 6x4 M. ตั้งอยู่สี่แยกตลาดฉัตรไชย ถ.เพชรเกษม จังหวัดประจวบคีรีขันธ์",
        traffic: "low",
        viewersPerDay: 752000,
    },
    {
        id: 57,
        name: "แยกห้างเพชรทอง ถ.สุรินทร์ฤาไชย",
        province: "เพชรบุรี",
        region: "west",
        latitude: 13.1078896,
        longitude: 99.9494106,
        size: "medium",
        dimensions: "4x3 M.",
        showTimes: "07.00 - 21.00 น.",
        timing: "14 Hrs.",
        address: "แยกห้างเพชรทอง ถ.สุรินทร์ฤาไชย",
        description: "จอ LED 4x3 M. ตั้งอยู่แยกห้างเพชรทอง ถ.สุรินทร์ฤาไชย จังหวัดเพชรบุรี",
        traffic: "medium",
        viewersPerDay: 1122325,
    },
    {
        id: 58,
        name: "สี่แยก VL Hotel หาดใหญ่",
        province: "สงขลา",
        region: "south",
        latitude: 7.0059166,
        longitude: 100.4713182,
        size: "medium",
        dimensions: "4x6 M.",
        showTimes: "07.00 - 21.00 น.",
        timing: "14 Hrs.",
        address: "สี่แยก VL Hotel หาดใหญ่",
        description: "จอ LED 4x6 M. ตั้งอยู่สี่แยก VL Hotel หาดใหญ่ จังหวัดสงขลา",
        traffic: "medium",
        viewersPerDay: 1725600,
    },
    {
        id: 59,
        name: "แยกวงเวียนหอนาฬิกาสงขลา",
        province: "สงขลา",
        region: "south",
        latitude: 7.2026,
        longitude: 100.59189,
        size: "medium",
        dimensions: "4x6 M.",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "แยกวงเวียนหอนาฬิกาสงขลา",
        description: "จอ LED 4x6 M. ตั้งอยู่แยกวงเวียนหอนาฬิกาสงขลา จังหวัดสงขลา",
        traffic: "medium",
        viewersPerDay: 1658000,
    },
    {
        id: 60,
        name: "สี่แยกมหาวิทยาลัยสงขลานครินทร์",
        province: "สงขลา",
        region: "south",
        latitude: 7.008362,
        longitude: 100.493872,
        size: "medium",
        dimensions: "5x9 M.",
        showTimes: "06.00 - 21.00 น.",
        timing: "15 Hrs.",
        address: "สี่แยกมหาวิทยาลัยสงขลานครินทร์",
        description: "จอ LED 5x9 M. ตั้งอยู่สี่แยกมหาวิทยาลัยสงขลานครินทร์ จังหวัดสงขลา",
        traffic: "high",
        viewersPerDay: 2565350,
    },
    {
        id: 61,
        name: "สามแยกประตู 109 ของมหาวิทยาลับสงขลานครินทร์",
        province: "สงขลา",
        region: "south",
        latitude: 7.00166,
        longitude: 100.50125,
        size: "medium",
        dimensions: "6x4 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "15 Hrs.",
        address: "สามแยกประตู 109 ของมหาวิทยาลับสงขลานครินทร์",
        description: "จอ LED 6x4 M. ตั้งอยู่สามแยกประตู 109 ของมหาวิทยาลับสงขลานครินทร์ จังหวัดสงขลา",
        traffic: "high",
        viewersPerDay: 2575350,
    },
    {
        id: 62,
        name: "สี่แยกโลตัสภูเก็ต ถนนพระภูเก็ตแก้ว",
        province: "ภูเก็ต",
        region: "south",
        latitude: 7.905876,
        longitude: 98.3669027,
        size: "medium",
        dimensions: "7x12 M.",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "สี่แยกโลตัสภูเก็ต ถนนพระภูเก็ตแก้ว",
        description: "จอ LED 7x12 M. ตั้งอยู่สี่แยกโลตัสภูเก็ต ถนนพระภูเก็ตแก้ว จังหวัดภูเก็ต",
        traffic: "very_high",
        viewersPerDay: 4553040,
    },
    {
        id: 63,
        name: "จอ sound gallery ภูเก็ต",
        province: "ภูเก็ต",
        region: "south",
        latitude: 7.884536,
        longitude: 98.379841,
        size: "medium",
        dimensions: "4x3 M.",
        showTimes: "06.30-10.30 น. และ 16.00 - 24.00",
        timing: "17.5 Hrs.",
        address: "จอ sound gallery ภูเก็ต",
        description: "จอ LED 4x3 M. ตั้งอยู่จอ sound gallery ภูเก็ต จังหวัดภูเก็ต",
        traffic: "medium",
        viewersPerDay: 1127300,
    },
    {
        id: 64,
        name: "ถนนเฉลิมพระเกียรติ ร.9",
        province: "ภูเก็ต",
        region: "south",
        latitude: 7.905068,
        longitude: 98.367925,
        size: "medium",
        dimensions: "10x19 M.",
        showTimes: "06.00 - 23.00 น.",
        timing: "17 Hrs.",
        address: "ถนนเฉลิมพระเกียรติ ร.9",
        description: "จอ LED 10x19 M. ตั้งอยู่ถนนเฉลิมพระเกียรติ ร.9 จังหวัดภูเก็ต",
        traffic: "very_high",
        viewersPerDay: 4553040,
    },
    {
        id: 65,
        name: "สี่แยกโรงแรมบีทู สุราษฎร์ธานี บูติค",
        province: "สุราษฎร์ธานี",
        region: "south",
        latitude: 9.1382636,
        longitude: 99.3218157,
        size: "medium",
        dimensions: "4x7 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "สี่แยกโรงแรมบีทู สุราษฎร์ธานี บูติค",
        description: "จอ LED 4x7 M. ตั้งอยู่สี่แยกโรงแรมบีทู สุราษฎร์ธานี บูติค จังหวัดสุราษฎร์ธานี",
        traffic: "medium",
        viewersPerDay: 1368000,
    },
    {
        id: 66,
        name: "รร.ซีบีดี",
        province: "สุราษฎร์ธานี",
        region: "south",
        latitude: 9.1435288,
        longitude: 99.325035,
        size: "medium",
        dimensions: "4x6 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "รร.ซีบีดี",
        description: "จอ LED 4x6 M. ตั้งอยู่รร.ซีบีดี จังหวัดสุราษฎร์ธานี",
        traffic: "medium",
        viewersPerDay: 1316400,
    },
    {
        id: 67,
        name: "สี่แยกคูขวาง",
        province: "นครศรีธรรมราช",
        region: "south",
        latitude: 8.4411556,
        longitude: 99.9698212,
        size: "medium",
        dimensions: "3x5 M.",
        showTimes: "04.00 - 24.00 น.",
        timing: "20 Hrs.",
        address: "สี่แยกคูขวาง",
        description: "จอ LED 3x5 M. ตั้งอยู่สี่แยกคูขวาง จังหวัดนครศรีธรรมราช",
        traffic: "low",
        viewersPerDay: 956960,
    },
    {
        id: 68,
        name: "สามแยกชินตา (สามแยกพรศิริกุล)",
        province: "ตรัง",
        region: "south",
        latitude: 7.558077,
        longitude: 99.614447,
        size: "medium",
        dimensions: "4x7 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "สามแยกชินตา (สามแยกพรศิริกุล)",
        description: "จอ LED 4x7 M. ตั้งอยู่สามแยกชินตา (สามแยกพรศิริกุล) จังหวัดตรัง",
        traffic: "medium",
        viewersPerDay: 1989000,
    },
    {
        id: 69,
        name: "สี่แยกโรงเรียนสตรียะลา",
        province: "ยะลา",
        region: "south",
        latitude: 6.5460895,
        longitude: 101.2834085,
        size: "medium",
        dimensions: "3x4 M.",
        showTimes: "07.00-21.00 น.",
        timing: "14 Hrs.",
        address: "สี่แยกโรงเรียนสตรียะลา",
        description: "จอ LED 3x4 M. ตั้งอยู่สี่แยกโรงเรียนสตรียะลา จังหวัดยะลา",
        traffic: "low",
        viewersPerDay: 656330,
    },
    {
        id: 70,
        name: "สี่แยกโรงพยาบาลปัตตานี",
        province: "ปัตตานี",
        region: "south",
        latitude: 6.8694704,
        longitude: 101.2504367,
        size: "medium",
        dimensions: "3x6 M.",
        showTimes: "07.00-22.00 น.",
        timing: "15 Hrs.",
        address: "สี่แยกโรงพยาบาลปัตตานี",
        description: "จอ LED 3x6 M. ตั้งอยู่สี่แยกโรงพยาบาลปัตตานี จังหวัดปัตตานี",
        traffic: "low",
        viewersPerDay: 768077,
    },
    {
        id: 71,
        name: "ถนนเพชรเกษม",
        province: "ชุมพร",
        region: "south",
        latitude: 10.580894,
        longitude: 99.11497,
        size: "medium",
        dimensions: "4x8 M.",
        showTimes: "06.00 - 22.00 น.",
        timing: "16 Hrs.",
        address: "ถนนเพชรเกษม",
        description: "จอ LED 4x8 M. ตั้งอยู่ถนนเพชรเกษม จังหวัดชุมพร",
        traffic: "high",
        viewersPerDay: 2759351,
    },
    {
        id: 72,
        name: "สี่แยกคลองจิหลาด",
        province: "กระบี่",
        region: "south",
        latitude: 8.0835121,
        longitude: 98.8955985,
        size: "medium",
        dimensions: "3x8 M.",
        showTimes: "07.00 - 21.00 น.",
        timing: "14 Hrs.",
        address: "สี่แยกคลองจิหลาด",
        description: "จอ LED 3x8 M. ตั้งอยู่สี่แยกคลองจิหลาด จังหวัดกระบี่",
        traffic: "low",
        viewersPerDay: 796811,
    }
];
